server:
  port: 3333

spring:
  application:
    name: CLOUD-API-GATEWAY
  boot:    admin:      client:        url: http://localhost:1111        
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome/{name}
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet/{name}
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*'